### ISSUE TITLE
Maintainership of this repository

### ISSUE THREAD

**Issue by turion** [dorchard/effect-monad#12]
I'd like to build some code based on effect-monad, but it seems like this repository is not very actively maintained. Two ideas:

* If @dorchard wants, I can maintain this repo, merge PRs, handle issues etc.
* If @dorchard doesn't want that, or doesn't respond, I could fork it. (Would especially do that if people have interest in an actively maintained effect-monad. Leave a thumbs up in that case.)

**Comment by dorchard** [comment]
Hi @turion, sorry for my lack of reply which does not help the issue. I am very thankful for the offer of maintainership. How kind! I would like to retain some control but I am very happy to receive pull requests fixing issues and to include you as an author?

**Comment by dorchard** [comment]
Additionally, I am hoping to do more work on this now and be a bit more active with it. I've let things slide.

**Comment by turion** [comment]
Ok, I might dust off some PRs and send them your way :) I haven't touched the code since a while anymore, so I'm not sure when I'll come around to this.
