### ISSUE TITLE
Why not a bit of Template Haskell for Var introduction?

### ISSUE THREAD

**Issue by rrnewton** [dorchard/effect-monad#4]
I.e. instead of:

``` Haskell
x_var = Var::(Var "x")
```

Perhaps `$(var x)` at each use site of `x_var`?

E.g. [in this example](https://github.com/dorchard/effect-monad/blob/master/examples/State.hs).

**Comment by dorchard** [comment]
Good question. I believe that Type Application in GHC 8 meets this need well. 
`Var @ "x"` I think would be the right syntax. I will try to do an update of this example using this style at some point.

**Comment by dorchard** [comment]
There is now an example of this:
https://github.com/dorchard/effect-monad/blob/master/examples/ExtensibleState.hs

I think that the type application approach is preferable to adding Template Haskell (in terms of overhead) but it could make a nice option still as a module?
