### ISSUE TITLE
Lift base version requirement for GHC 8

### ISSUE THREAD

**Issue by jbracker** [dorchard/effect-monad#7]
Currently the package requires base < 4.9. This makes the package incompatible with GHC 8.0.1, because the delivered version there is 4.9.0.0.

I suggest simply requiring base < 5 for now.

I would appreciate if you can upload a new version of the package quickly.

**Comment by dorchard** [comment]
Thanks Jan. I will upload a new version to Hackage today- I have a few other issue to deal with on this package and its sister package `type-level-sets`.

**Comment by jbracker** [comment]
Thank you for the quick response and accepting the pull request!

**Comment by jbracker** [comment]
Any updates on the status of the new version for Hackage?

**Comment by jbracker** [comment]
Is the new version of this coming to Hackage any time soon?

**Comment by dorchard** [comment]
Done! Thanks very much for the bump, and sorry for the delay.

**Comment by jbracker** [comment]
Thank you for updating the packages!
